# Generated by Django 6.0.4 on 2026-04-29 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IssuanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(help_text='Row serial number from the register')),
                ('date', models.DateField()),
                ('fiscal_year', models.CharField(default='2025-26', max_length=10)),
                ('month', models.CharField(blank=True, max_length=20)),
                ('sheet_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuances', to='store.department')),
            ],
            options={
                'ordering': ['-date', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveSmallIntegerField(help_text='Serial number from the register (1–118)', unique=True)),
                ('name', models.CharField(max_length=300)),
                ('unit', models.CharField(choices=[('ream', 'Ream'), ('piece', 'Piece'), ('box', 'Box'), ('roll', 'Roll'), ('set', 'Set'), ('kg', 'Kg'), ('litre', 'Litre'), ('packet', 'Packet'), ('other', 'Other')], default='piece', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.category')),
            ],
            options={
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='IssuanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='store.issuancerecord')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance_lines', to='store.stockitem')),
            ],
            options={
                'ordering': ['item__item_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='issuancerecord',
            constraint=models.UniqueConstraint(fields=('serial_number', 'date', 'department', 'fiscal_year', 'sheet_number'), name='unique_issuance_register_entry'),
        ),
        migrations.AlterUniqueTogether(
            name='issuanceline',
            unique_together={('record', 'item')},
        ),
    ]
