# Generated by Django 6.0.4 on 2026-05-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_districtoffice_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circleofficename', models.CharField(max_length=100)),
                ('officeaddress', models.CharField(blank=True, max_length=250, null=True)),
                ('headoffice_id', models.IntegerField(default=0)),
                ('slno', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'circleoffice',
                'ordering': ['slno'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designationname', models.CharField(max_length=100)),
                ('class_field', models.CharField(blank=True, db_column='class', default='0', max_length=50)),
                ('grade_id', models.IntegerField(default=0)),
                ('nopost', models.IntegerField(default=0)),
                ('desigslno', models.IntegerField(default=0)),
                ('officerornot_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'designation',
                'ordering': ['desigslno'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divcode', models.CharField(max_length=3)),
                ('divisionname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'division',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='districtoffice',
            options={'ordering': ['orderno', 'districtofficename']},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['orderno', 'officename']},
        ),
        migrations.RemoveField(
            model_name='districtoffice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='office',
            name='district_office',
        ),
        migrations.RemoveField(
            model_name='office',
            name='name',
        ),
        migrations.AddField(
            model_name='districtoffice',
            name='districtofficename',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='districtoffice',
            name='nomanp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='districtoffice',
            name='officeaddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='districtoffice',
            name='orderno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='office',
            name='activity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='office',
            name='districtoffice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='store.districtoffice'),
        ),
        migrations.AddField(
            model_name='office',
            name='officeaddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='officename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='orderno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='districtoffice',
            name='circleoffice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_offices', to='store.circleoffice'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districtname', models.CharField(max_length=100)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='store.division')),
            ],
            options={
                'db_table': 'district',
                'ordering': ['districtname'],
            },
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upazilaname', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upazilas', to='store.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upazilas', to='store.division')),
            ],
            options={
                'db_table': 'upazila',
                'ordering': ['upazilaname'],
            },
        ),
    ]
