# Generated by Django 6.0.4 on 2026-05-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_circleoffice_designation_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officename', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'headoffice',
            },
        ),
    ]
