# Generated by Django 6.0.4 on 2026-05-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_purchasehead_remark_invoiceno_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchercode',
            name='shortname',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
