# Generated by Django 6.0.4 on 2026-05-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_vouchercode_shortname_max5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskname', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'desk',
                'ordering': ['deskname'],
            },
        ),
        migrations.CreateModel(
            name='PurRetHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.CharField(blank=True, max_length=20)),
                ('purinvoiceno', models.CharField(blank=True, max_length=20, null=True)),
                ('invoicedate', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('cruser_id', models.IntegerField(default=0)),
                ('upduser_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purret_heads', to='store.monthlist')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purret_heads', to='store.supplier')),
                ('vouchercode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purret_heads', to='store.vouchercode')),
                ('yearlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purret_heads', to='store.yearlist')),
            ],
            options={
                'db_table': 'purrethead',
                'ordering': ['-invoicedate', 'invoiceno'],
            },
        ),
        migrations.CreateModel(
            name='PurRetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opnbalance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clbalance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purrate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purprice', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salesrate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cruser_id', models.IntegerField(default=0)),
                ('upduser_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purret_items', to='store.product')),
                ('purrethead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.purrethead')),
            ],
            options={
                'db_table': 'purretitem',
                'ordering': ['product__productname'],
            },
        ),
    ]
