# Generated by Django 6.0.4 on 2026-05-20 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_add_customer_sales_slret_replace_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.CharField(blank=True, max_length=20)),
                ('invoicedate', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('cruser_id', models.IntegerField(default=0)),
                ('upduser_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_heads', to='backend.customer')),
                ('monthlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_heads', to='backend.monthlist')),
                ('vouchercode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_heads', to='backend.vouchercode')),
                ('yearlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='damage_heads', to='backend.yearlist')),
            ],
            options={
                'db_table': 'damagehead',
                'ordering': ['-invoicedate', 'invoiceno'],
            },
        ),
        migrations.CreateModel(
            name='DamageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opnbalance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('clbalance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purrate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damagerate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damageprice', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cruser_id', models.IntegerField(default=0)),
                ('upduser_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('damagehead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.damagehead')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_items', to='backend.product')),
            ],
            options={
                'db_table': 'damageitem',
                'ordering': ['product__productname'],
            },
        ),
    ]
