# Generated by Django 6.0.4 on 2026-08-29 19:02
# Hand-edited: these tables already exist under their original names from
# when this app was called "store" (see AUTH_USER_MODEL/app rename to
# "backend"). Only Django's model state needs updating, not the schema.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_budgethead_customer_nullable'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='category',
                    table='store_category',
                ),
                migrations.AlterModelTable(
                    name='department',
                    table='store_department',
                ),
                migrations.AlterModelTable(
                    name='districtoffice',
                    table='store_districtoffice',
                ),
                migrations.AlterModelTable(
                    name='issuanceline',
                    table='store_issuanceline',
                ),
                migrations.AlterModelTable(
                    name='issuancerecord',
                    table='store_issuancerecord',
                ),
                migrations.AlterModelTable(
                    name='office',
                    table='store_office',
                ),
                migrations.AlterModelTable(
                    name='stockitem',
                    table='store_stockitem',
                ),
                migrations.AlterModelTable(
                    name='user',
                    table='store_user',
                ),
                migrations.AlterModelTable(
                    name='userrole',
                    table='store_userrole',
                ),
            ],
        ),
    ]
